In [7]:
import pandas as pd
from pprint import pprint

In [ ]:
def dim_location_dataframe(**dataframes) -> pd.DataFrame:
    """
    Create the location dimension DataFrame from the extracted raw address data.

    Parameters:
    -----------
    dataframes : dict
        Dictionary containing raw DataFrames extracted from source tables.
        Must contain an 'address' DataFrame.

    Returns:
    --------
    pd.DataFrame
        A DataFrame representing the location dimension with columns:
        'address_id', 'address_line_1', 'address_line_2', 'district', 'city',
        'postal_code', 'country', and 'phone'.

    Raises:
    -------
    ValueError
        If the 'address' table is missing or any error occurs during transformation.
    """

    required_keys = ["address"]

    for key in required_keys:
        if key not in dataframes:
            raise ValueError(f"Error: Missing required dataframe '{key}'.")

    address_df = dataframes.get("address")
    try:
        dim_location = address_df[
            [
                "address_id",
                "address_line_1",
                "address_line_2",
                "district",
                "city",
                "postal_code",
                "country",
                "phone",
            ]
        ].drop_duplicates()
        dim_location.rename(columns={"address_id": "location_id"}, inplace=True)

        return dim_location

    except Exception as e:
        raise ValueError(f"Error creating dim_location: {e}")

In [9]:
address_df = pd.read_parquet(
    "../sql_local_tests/seed_data/address_2022-11-3_14-20-49_962000.parquet"
)
pprint(address_df)

    address_id           address_line_1    address_line_2         district  \
0            1          6826 Herzog Via              None             Avon
1            2        179 Alexie Cliffs              None             None
2            3         148 Sincere Fort              None             None
3            4       6102 Rogahn Skyway              None     Bedfordshire
4            5        34177 Upton Track              None             None
5            6        846 Kailey Island              None             None
6            7     75653 Ernestine Ways              None  Buckinghamshire
7            8       0579 Durgan Common              None             None
8            9        644 Edward Garden              None          Borders
9           10        49967 Kaylah Flat  Tremaine Circles     Bedfordshire
10          11      249 Bernier Mission              None  Buckinghamshire
11          12  6461 Ernesto Expressway              None        Berkshire
12          13          80828 Arch Dale   Torphy Turnpike             None
13          14       84824 Bryce Common    Grady Turnpike             None
14          15   605 Haskell Trafficway      Axel Freeway             None
15          16       511 Orin Extension      Cielo Radial  Buckinghamshire
16          17          962 Koch Drives              None             None
17          18        58805 Sibyl Cliff    Leuschke Glens     Bedfordshire
18          19         0283 Cole Corner     Izabella Ways  Buckinghamshire
19          20      22073 Klein Landing              None             None
20          21      389 Georgette Ridge              None   Cambridgeshire
21          22      364 Goodwin Streets              None             None
22          23    822 Providenci Spring              None        Berkshire
23          24       8434 Daren Freeway              None             None
24          25        253 Ullrich Inlet        Macey Wall          Borders
25          26       522 Pacocha Branch              None     Bedfordshire
26          27    7212 Breitenberg View       Nora Bridge  Buckinghamshire
27          28      079 Horacio Landing              None             None
28          29     37736 Heathcote Lock       Noemy Pines             None
29          30       0336 Ruthe Heights              None  Buckinghamshire

                  city postal_code                                country  \
0    New Patienceburgh       28441                                 Turkey
1          Aliso Viejo  99305-7380                             San Marino
2         Lake Charles       89360                                  Samoa
3            Olsonside       47518                      Republic of Korea
4       Fort Shadburgh  55993-8850                 Bosnia and Herzegovina
5          Kendraburgh       08841                               Zimbabwe
6        North Deshaun       02813                          Faroe Islands
7              Suffolk  56693-0660                         United Kingdom
8             New Tyra  30825-5672                              Australia
9        Beaulahcester       89470  Democratic People's Republic of Korea
10      Corpus Christi  85111-9300                                  Japan
11           Pricetown  37167-0340                             Tajikistan
12        Shanahanview  60728-5019              Bouvet Island (Bouvetoya)
13          Maggiofurt  50899-1522                                   Iraq
14         East Bobbie  88253-4257      Heard Island and McDonald Islands
15         South Wyatt  04524-5341                                Iceland
16          Hackensack  95316-4738                              Indonesia
17           Lake Arne       63808                               Kiribati
18  West Briellecester       01138                           Sierra Leone
19              Pueblo       91445                      Republic of Korea
20              Fresno  91510-3655                                Bolivia
21          Sayreville  85544-4254           Svalbard & Jan Mayen Islands
22           Derekport       25541                       Papua New Guinea
23        New Torrance       17110                    Antigua and Barbuda
24          East Arvel  35397-9952                                  Sudan
25                Napa  77211-4519                         American Samoa
26        Oakland Park       77499                                   Guam
27               Utica       93045                                Austria
28         Bartellview  42400-5199                                  Congo
29       Lake Myrlfurt  94545-4284            Falkland Islands (Malvinas)

          phone              created_at            last_updated
0   1803 637401 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
1   9621 880720 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
2   0730 783349 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
3   1239 706295 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
4   0081 009772 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
5   0447 798320 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
6   1373 796260 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
7   8935 157571 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
8   0768 748652 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
9   4949 998070 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
10  0222 525870 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
11  4757 757948 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
12  8806 209655 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
13  3316 955887 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
14  9687 937447 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
15  2372 180716 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
16  5507 549583 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
17  0168 407254 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
18  1753 158314 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
19  4003 678621 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
20  8697 474676 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
21  0847 468066 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
22  4111 801405 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
23  5582 055380 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
24  0021 366201 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
25  5794 359212 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
26  2949 665163 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
27  7772 084705 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
28  1684 702261 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962
29  1083 286132 2022-11-03 14:20:49.962 2022-11-03 14:20:49.962

In [12]:
dim_location_df = dim_location_dataframe(address=address_df)
pprint(dim_location_df)

    location_id           address_line_1    address_line_2         district  \
0             1          6826 Herzog Via              None             Avon
1             2        179 Alexie Cliffs              None             None
2             3         148 Sincere Fort              None             None
3             4       6102 Rogahn Skyway              None     Bedfordshire
4             5        34177 Upton Track              None             None
5             6        846 Kailey Island              None             None
6             7     75653 Ernestine Ways              None  Buckinghamshire
7             8       0579 Durgan Common              None             None
8             9        644 Edward Garden              None          Borders
9            10        49967 Kaylah Flat  Tremaine Circles     Bedfordshire
10           11      249 Bernier Mission              None  Buckinghamshire
11           12  6461 Ernesto Expressway              None        Berkshire
12           13          80828 Arch Dale   Torphy Turnpike             None
13           14       84824 Bryce Common    Grady Turnpike             None
14           15   605 Haskell Trafficway      Axel Freeway             None
15           16       511 Orin Extension      Cielo Radial  Buckinghamshire
16           17          962 Koch Drives              None             None
17           18        58805 Sibyl Cliff    Leuschke Glens     Bedfordshire
18           19         0283 Cole Corner     Izabella Ways  Buckinghamshire
19           20      22073 Klein Landing              None             None
20           21      389 Georgette Ridge              None   Cambridgeshire
21           22      364 Goodwin Streets              None             None
22           23    822 Providenci Spring              None        Berkshire
23           24       8434 Daren Freeway              None             None
24           25        253 Ullrich Inlet        Macey Wall          Borders
25           26       522 Pacocha Branch              None     Bedfordshire
26           27    7212 Breitenberg View       Nora Bridge  Buckinghamshire
27           28      079 Horacio Landing              None             None
28           29     37736 Heathcote Lock       Noemy Pines             None
29           30       0336 Ruthe Heights              None  Buckinghamshire

                  city postal_code                                country  \
0    New Patienceburgh       28441                                 Turkey
1          Aliso Viejo  99305-7380                             San Marino
2         Lake Charles       89360                                  Samoa
3            Olsonside       47518                      Republic of Korea
4       Fort Shadburgh  55993-8850                 Bosnia and Herzegovina
5          Kendraburgh       08841                               Zimbabwe
6        North Deshaun       02813                          Faroe Islands
7              Suffolk  56693-0660                         United Kingdom
8             New Tyra  30825-5672                              Australia
9        Beaulahcester       89470  Democratic People's Republic of Korea
10      Corpus Christi  85111-9300                                  Japan
11           Pricetown  37167-0340                             Tajikistan
12        Shanahanview  60728-5019              Bouvet Island (Bouvetoya)
13          Maggiofurt  50899-1522                                   Iraq
14         East Bobbie  88253-4257      Heard Island and McDonald Islands
15         South Wyatt  04524-5341                                Iceland
16          Hackensack  95316-4738                              Indonesia
17           Lake Arne       63808                               Kiribati
18  West Briellecester       01138                           Sierra Leone
19              Pueblo       91445                      Republic of Korea
20              Fresno  91510-3655                                Bolivia
21          Sayreville  85544-4254           Svalbard & Jan Mayen Islands
22           Derekport       25541                       Papua New Guinea
23        New Torrance       17110                    Antigua and Barbuda
24          East Arvel  35397-9952                                  Sudan
25                Napa  77211-4519                         American Samoa
26        Oakland Park       77499                                   Guam
27               Utica       93045                                Austria
28         Bartellview  42400-5199                                  Congo
29       Lake Myrlfurt  94545-4284            Falkland Islands (Malvinas)

          phone
0   1803 637401
1   9621 880720
2   0730 783349
3   1239 706295
4   0081 009772
5   0447 798320
6   1373 796260
7   8935 157571
8   0768 748652
9   4949 998070
10  0222 525870
11  4757 757948
12  8806 209655
13  3316 955887
14  9687 937447
15  2372 180716
16  5507 549583
17  0168 407254
18  1753 158314
19  4003 678621
20  8697 474676
21  0847 468066
22  4111 801405
23  5582 055380
24  0021 366201
25  5794 359212
26  2949 665163
27  7772 084705
28  1684 702261
29  1083 286132